"""Generate an optional SYN budget for a direct ZHTPS listener.

No proxy or HTTP service is required. Rates count SYN packets, including retries,
across the chosen listener. Generation writes files only; it never changes the
host firewall. Apply or remove the named table on the listener's host.
"""

import argparse
from dataclasses import asdict, dataclass
import ipaddress
import json
from pathlib import Path
import re


@dataclass(frozen=True)
class Options:
    listen_address: str
    listen_port: int
    interface: str
    connection_rate: int
    connection_burst: int
    reset_rate: int
    reset_burst: int
    table: str = "zhtps_connections"

    def validate(self):
        address = ipaddress.ip_address(self.listen_address)
        if address.is_unspecified or address.is_multicast or "%" in self.listen_address:
            raise ValueError("use an explicit unicast listener IP without a scope suffix")
        if not 1 <= self.listen_port <= 65535:
            raise ValueError("listen port must be in 1..65535")
        if not re.fullmatch(r"[A-Za-z0-9_.:-]{1,15}", self.interface):
            raise ValueError("invalid interface name")
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]{0,47}", self.table):
            raise ValueError("invalid nftables table name")
        for amount in (self.connection_rate, self.connection_burst,
                       self.reset_rate, self.reset_burst):
            if not 1 <= amount <= 1_000_000_000:
                raise ValueError("calibrated rates and bursts must be explicit positive values <= 1000000000")


def nft_config(options):
    options.validate()
    family = "ip6" if ipaddress.ip_address(options.listen_address).version == 6 else "ip"
    return f'''# Generated by deploy/connections.py. SYN packets, including retries, are counted.
# Only this explicit listener/interface is policed; existing connections pass.
table inet {options.table} {{
    counter syn_attempts {{ }}
    counter syn_over_limit {{ }}
    counter syn_resets {{ }}
    counter syn_drops {{ }}
    chain reject_connection {{
        limit rate {options.reset_rate}/second burst {options.reset_burst} packets counter name syn_resets reject with tcp reset
        counter name syn_drops drop
    }}
    chain incoming {{
        type filter hook prerouting priority -300; policy accept;
        iifname "{options.interface}" {family} daddr {options.listen_address} tcp dport {options.listen_port} tcp flags & (syn | ack) == syn counter name syn_attempts limit rate over {options.connection_rate}/second burst {options.connection_burst} packets counter name syn_over_limit jump reject_connection
    }}
}}
'''


def write_bundle(options, output):
    options.validate()
    files = {
        "connections.nft": nft_config(options),
        "remove-connections.nft": f"delete table inet {options.table}\n",
        "limits.json": json.dumps(asdict(options), indent=2) + "\n",
    }
    if any((output / name).exists() for name in files):
        raise ValueError("output already contains a configuration; choose a new directory")
    output.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        # Exclusive creation also rejects symlinks and files appearing after the precheck.
        with (output / name).open("x", encoding="utf-8") as destination:
            destination.write(content)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--listen-address", required=True)
    parser.add_argument("--interface", required=True)
    parser.add_argument("--table", default="zhtps_connections")
    for name in ("listen-port", "connection-rate", "connection-burst", "reset-rate", "reset-burst"):
        parser.add_argument("--" + name, type=int, required=True)
    arguments = vars(parser.parse_args())
    output = arguments.pop("output").resolve()
    try:
        write_bundle(Options(**arguments), output)
    except (ValueError, OSError) as error:
        parser.error(str(error))
    print(f"Wrote direct-listener connection policy to {output}")


if __name__ == "__main__":
    main()
