"""Generate an optional NGINX request gate and an independent early SYN policer.

All rates are explicit aggregate budgets for one ingress instance. Generation
only writes files; apply the scoped nftables table on the ingress host after
reviewing its interface/address/port. No server defaults are changed.
"""

import argparse
from dataclasses import asdict, dataclass
import ipaddress
import json
from pathlib import Path
import re

import connections


@dataclass(frozen=True)
class Options:
    listen_address: str
    listen_port: int
    origin_address: str
    origin_port: int
    interface: str
    request_rate: int
    request_burst: int
    connection_rate: int
    connection_burst: int
    reset_rate: int
    reset_burst: int
    origin_workers: int = 1
    origin_slots: int = 512
    origin_active_per_worker: int | None = None
    proxy_workers: int = 1
    proxy_connections: int = 4096
    max_body_bytes: int = 64 * 1024 * 1024
    keepalive_requests: int = 1000
    access_log: bool = False
    table: str = "zhtps_ingress"

    def validate(self):
        for address in (self.listen_address, self.origin_address):
            parsed = ipaddress.ip_address(address)
            if parsed.is_unspecified or parsed.is_multicast or "%" in address:
                raise ValueError("use explicit unicast listen and origin IP addresses without scope suffixes")
        for port in (self.listen_port, self.origin_port):
            if not 1 <= port <= 65535:
                raise ValueError("ports must be in 1..65535")
        if (ipaddress.ip_address(self.listen_address), self.listen_port) == (
                ipaddress.ip_address(self.origin_address), self.origin_port):
            raise ValueError("ingress cannot proxy to its own listener")
        if not re.fullmatch(r"[A-Za-z0-9_.:-]{1,15}", self.interface):
            raise ValueError("invalid interface name")
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]{0,47}", self.table):
            raise ValueError("invalid nftables table name")
        for rate in (self.request_rate, self.connection_rate, self.reset_rate):
            if not 1 <= rate <= 1_000_000_000:
                raise ValueError("calibrated rates must be explicit positive values <= 1000000000")
        for burst in (self.connection_burst, self.reset_burst):
            if not 1 <= burst <= 1_000_000_000:
                raise ValueError("connection and reset bursts must be positive")
        if not 0 <= self.request_burst <= 1_000_000_000:
            raise ValueError("request burst must be in 0..1000000000")
        if not 1 <= self.origin_workers <= 256 or not 1 <= self.origin_slots <= 8176:
            raise ValueError("invalid origin worker/connection budget")
        if self.origin_active_per_worker is not None and not 1 <= self.origin_active_per_worker <= self.origin_slots:
            raise ValueError("invalid origin active-request budget")
        if not 1 <= self.proxy_workers <= 256 or not 16 <= self.proxy_connections <= 1_000_000:
            raise ValueError("invalid proxy worker/connection budget")
        if not 1 <= self.max_body_bytes <= 2**32 - 1 or not 1 <= self.keepalive_requests <= 2**32 - 1:
            raise ValueError("invalid body/connection lifetime bound")
        if self.connection_budget() < 2 * self.proxy_workers:
            raise ValueError("origin budget must leave an active and an idle slot per proxy worker")
        if 2 * self.active_budget() + self.idle_per_worker() >= self.proxy_connections:
            raise ValueError("proxy connection budget must leave room for both client and origin sockets")

    def connection_budget(self):
        return self.origin_workers * max(1, self.origin_slots * 3 // 4)

    def idle_per_worker(self):
        return min(32, self.connection_budget() // (2 * self.proxy_workers))

    def active_budget(self):
        available = self.connection_budget() - self.proxy_workers * self.idle_per_worker()
        if self.origin_active_per_worker is not None:
            available = min(available, self.origin_workers * self.origin_active_per_worker)
        return available


def endpoint(address, port):
    return f"[{address}]:{port}" if ipaddress.ip_address(address).version == 6 else f"{address}:{port}"


def nginx_config(options):
    options.validate()
    burst = f" burst={options.request_burst}" if options.request_burst else ""
    access = "access_log logs/access.json admission buffer=256k flush=1s;" if options.access_log else "access_log off;"
    return f'''# Generated by deploy/ingress.py. NGINX 1.30 or newer; budgets are aggregate.
worker_processes {options.proxy_workers};
pid logs/nginx.pid;
error_log logs/error.log crit;
events {{ worker_connections {options.proxy_connections}; }}
http {{
    # A constant key shares one budget across clients and proxy workers.
    limit_req_zone "zhtps_origin" zone=requests:64k rate={options.request_rate}r/s;
    limit_conn_zone "zhtps_origin" zone=active:64k;
    log_format admission escape=json '{{"status":$status,"limit":"$limit_req_status",'
        '"upstream":"$upstream_status","request_time":$request_time}}';
    {access}
    client_body_temp_path body_temp;
    proxy_temp_path proxy_temp;
    client_header_timeout 5s;
    client_body_timeout 30s;
    send_timeout 5s;
    reset_timedout_connection on;
    keepalive_timeout 15s;
    keepalive_requests {options.keepalive_requests};
    client_max_body_size {options.max_body_bytes};
    upstream origin {{
        zone origin 64k;
        server {endpoint(options.origin_address, options.origin_port)} max_conns={options.active_budget()} max_fails=0;
        # Active + idle connections remain inside the configured origin budget.
        keepalive {options.idle_per_worker()};
        keepalive_timeout 10s;
        keepalive_requests {options.keepalive_requests};
    }}
    server {{
        listen {endpoint(options.listen_address, options.listen_port)};
        server_name zhtps_ingress;
        limit_req_status 503;
        limit_req_log_level notice;
        limit_conn_status 503;
        limit_conn_log_level notice;
        location / {{
            # No waiting room for excess requests or busy origin connections.
            limit_req zone=requests{burst} nodelay;
            limit_conn active {options.active_budget()};
            proxy_pass http://origin;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $http_host;
            proxy_request_buffering off;
            proxy_buffering off;
            proxy_next_upstream off;
            proxy_connect_timeout 1s;
            proxy_read_timeout 5s;
            proxy_send_timeout 5s;
        }}
    }}
}}
'''


def nft_config(options):
    options.validate()
    return connections.nft_config(connections.Options(
        listen_address=options.listen_address, listen_port=options.listen_port,
        interface=options.interface, connection_rate=options.connection_rate,
        connection_burst=options.connection_burst, reset_rate=options.reset_rate,
        reset_burst=options.reset_burst, table=options.table))


def write_bundle(options, output, origin_config=None):
    options.validate()
    output.mkdir(parents=True, exist_ok=True)
    files = {"nginx.conf": nginx_config(options), "connections.nft": nft_config(options),
             "remove-connections.nft": f"delete table inet {options.table}\n",
             "limits.json": json.dumps(dict(asdict(options), origin_connection_budget=options.connection_budget(),
                                            origin_active_budget=options.active_budget(),
                                            idle_connections_per_proxy_worker=options.idle_per_worker()), indent=2) + "\n"}
    if origin_config is not None:
        files["origin-config.json"] = json.dumps(origin_config, indent=2) + "\n"
    if any((output / name).exists() for name in files):
        raise ValueError("output already contains a configuration; choose a new directory")
    for directory in ("logs", "body_temp", "proxy_temp"):
        (output / directory).mkdir(exist_ok=True)
    for name, content in files.items():
        # Exclusive creation also rejects symlinks and files appearing after the precheck.
        with (output / name).open("x", encoding="utf-8") as destination:
            destination.write(content)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--origin-config", type=Path, help="effective /debug/config snapshot; supplies worker/connection/active budgets")
    parser.add_argument("--origin-workers", type=int)
    parser.add_argument("--origin-slots", type=int)
    parser.add_argument("--origin-active-per-worker", type=int)
    for name in ("listen-address", "origin-address", "interface"):
        parser.add_argument("--" + name, required=True)
    for name in ("listen-port", "origin-port", "request-rate", "request-burst", "connection-rate",
                 "connection-burst", "reset-rate", "reset-burst"):
        parser.add_argument("--" + name, type=int, required=True)
    for name, default in (("proxy-workers", 1),
                          ("proxy-connections", 4096), ("max-body-bytes", 64 * 1024 * 1024),
                          ("keepalive-requests", 1000)):
        parser.add_argument("--" + name, type=int, default=default)
    parser.add_argument("--table", default="zhtps_ingress")
    parser.add_argument("--access-log", action="store_true")
    arguments = vars(parser.parse_args())
    output = arguments.pop("output").resolve()
    config_path = arguments.pop("origin_config")
    origin_config = None
    if config_path:
        origin_config = json.loads(config_path.read_text())
        captured = {"origin_workers": origin_config["workers"], "origin_slots": origin_config["max_connections"],
                    "origin_active_per_worker": origin_config.get("admission", {}).get("max_active")}
        for field, value in captured.items():
            if arguments[field] is not None and value is not None and arguments[field] != value:
                parser.error(f"{field} conflicts with the effective origin configuration")
            if arguments[field] is None:
                arguments[field] = value
    if arguments["origin_workers"] is None or arguments["origin_slots"] is None:
        parser.error("supply --origin-config or both --origin-workers and --origin-slots")
    try:
        write_bundle(Options(**arguments), output, origin_config)
    except (ValueError, OSError) as error:
        parser.error(str(error))
    print(f"Wrote ingress configuration to {output}")


if __name__ == "__main__":
    main()
